### ISSUE TITLE
Saving many of the same prefab seems to fail

### ISSUE THREAD

**Issue by Cookizza** [AlexMeesters/Component-Save-System#2] opened 2020-01-05 02:48 UTC
Hello,

Firstly thanks for making this great free plugin for the community!

I am having issues when trying to save 100+ of the same Resource/Prefab.

I am dropping marbles onto a plane using the plugins alternative Instantiation method.

Once I reload the game, on mobile or editor I find it's stopped saving the marbles after around 100 have been spawned.

I could put together a demo scene if you need but perhaps there's a simple explanation and I'm being thick :p

**Comment by AlexMeesters** [comment] 2020-01-05 11:09
Hello Cookizza, 

Thank you for using the plugin and reporting this issue!
I will investigate this issue now. If I fail to reproduce the error you are having, then I may need a demo scene. I'll make sure to comment here if that is the case.

**Comment by Cookizza** [comment] 2020-01-05 11:14
I am still having a look into this on my project.

Thanks for having a look with me, I am trying to simplify my project to see if I can locate the issue

edit: nope it is still happening even if i remove these types of objects :(

**Comment by Cookizza** [comment] 2020-01-05 11:22
It seems like the only differences in my project to the examples that come with the plugin is that I use Destroy(this.gameObject) on my saveable objects instead of visibility / enabled

**Comment by AlexMeesters** [comment] 2020-01-05 11:23
Okay, so I've ran some basic tests. I'm not able to reproduce the issue at the moment.
Tested with 300 spawned cubes with rigid body + saving of position , rotation and scale.
Also tested spawning 200 extra on the next load. And removing 100 manually through the editor. Results seem to stay consistent.

Is there a way for you to provide a small portion of your project that can display this issue?
Edit: I'm going to try using Destroy now

**Comment by AlexMeesters** [comment] 2020-01-05 11:28
Okay, I've been able to get a similar result. Where new objects somehow don't get saved. Investigating this now

**Comment by Cookizza** [comment] 2020-01-05 11:32
Thanks Alex, glad to hear we're getting somewhere.

If there's any info or work you'd like from me I'm happy to help

**Comment by AlexMeesters** [comment] 2020-01-05 11:38
It seems that objects with the same ID are getting spawned.
This explains why not all objects show up on restart.
Looks like I'm not doing any proper checking for already existing ID's upon spawn.

Writing fix for this now, which hopefully solves the issue.
I will comment here again once I've written a fix & will update the specified code on git.
You can then test the new script, so we can confirm it also works on your side.
I'll make sure to drop a link here to the specified script.

Thank you for contributing to help!

**Comment by AlexMeesters** [comment] 2020-01-05 12:06
You can check & try the new fix here (Just replace this script in your project):
https://github.com/AlexMeesters/Component-Save-System/blob/208f41b51f93589f27eea9e4b6d9f7656b66308e/Assets/Plugins/Lowscope/ComponentSaveSystem/Core/SaveInstanceManager.cs

Thank you for reporting this issue. Kind of a big oversight on my end to not add any proper checking. Somehow the issue never showed up on lower object counts. Please let me know if this solves the issue for you.

**Comment by Cookizza** [comment] 2020-01-05 12:15
That seems to have fixed it Alex, thanks so much!

**Comment by AlexMeesters** [comment] 2020-01-05 12:17
No problem, Glad this solved it! Thank you for pointing this issue out, I'm sure you prevented a lot of frustration for other users. I'll start uploading the fix to a unitypackage and asset store.

**Closed as completed by AlexMeesters** 2020-01-05 12:17 UTC
